set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m3)

file(GLOB WTK_ARM_TOOLCHAIN_HINTS
    "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/*/bin"
    "C:/Program Files/Arm GNU Toolchain arm-none-eabi/*/bin"
)

find_program(WTK_ARM_GCC arm-none-eabi-gcc HINTS ${WTK_ARM_TOOLCHAIN_HINTS} REQUIRED)
find_program(WTK_ARM_OBJCOPY arm-none-eabi-objcopy HINTS ${WTK_ARM_TOOLCHAIN_HINTS} REQUIRED)
find_program(WTK_ARM_SIZE arm-none-eabi-size HINTS ${WTK_ARM_TOOLCHAIN_HINTS} REQUIRED)
set(CMAKE_C_COMPILER "${WTK_ARM_GCC}")
set(CMAKE_ASM_COMPILER "${WTK_ARM_GCC}")
set(CMAKE_OBJCOPY "${WTK_ARM_OBJCOPY}" CACHE FILEPATH "Arm objcopy" FORCE)
set(CMAKE_SIZE "${WTK_ARM_SIZE}" CACHE FILEPATH "Arm size" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_EXECUTABLE_SUFFIX ".elf")

set(WTK_ARM_CPU_FLAGS "-mcpu=cortex-m3 -mthumb")

set(CMAKE_C_FLAGS_INIT "${WTK_ARM_CPU_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "${WTK_ARM_CPU_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${WTK_ARM_CPU_FLAGS}")

set(CMAKE_C_FLAGS_DEBUG_INIT "-Og -g3")
set(CMAKE_C_FLAGS_LAB_INIT "-Os -g3 -DWTK_LAB_BUILD=1")
set(CMAKE_C_FLAGS_RELEASE_INIT "-Os -g0 -DNDEBUG")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "")
set(CMAKE_EXE_LINKER_FLAGS_LAB_INIT "")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "")
